### ISSUE TITLE
Is this says codellama run only on CPU with this project?

### ISSUE THREAD

**Issue by bonuschild** [xNul/code-llama-for-vscode#11]
I saw that you mock `llama.cpp` but I still have gpu resources, event I also have enough cpu & RAM.

Just want to figure out it's right scene to deploying.

**Comment by xNul** [comment]
Code Llama runs on the GPU if you setup the codellama repository correctly. You have to install pytorch w/ CUDA support.

I'll close this issue since it has been so long and this probably answers your question. Let me know if you'd like to reopen it.
