### ISSUE TITLE
It seems like have a bug?

### ISSUE THREAD

**Issue by Arcmoon-Hu** [xNul/code-llama-for-vscode#5]
When run 13b version? I add a function seems like:
```
def run_text_completion(prompts):
    geneartor.text_completion(...)
```
It will be in loop before `self.geneaotor` in llama.geneartor method, and use `geneartor.chat_completion` it will be fine. I'm very confused.

**Comment by xNul** [comment]
It seems like this isn't a problem anymore so I'm going to close this issue. Let me know if you still have this problem and would like to reopen it.
