### ISSUE TITLE
Link for config doesnt work

### ISSUE THREAD

**Issue by BoazimMatrix** [xNul/code-llama-for-vscode#8]
Hey,
The link for the edited config file doesnt work.
and you update it? or just upload a config file as an example?

thank you

**Comment by SeitzB** [comment]
Is there Like A new way to do this or has anyone figured out, what to put into the config file?

**Comment by xNul** [comment]
I've updated the instructions and the code to support the latest version of Continue. I've archived the link this time so hopefully we won't have this problem again.

I'll close this issue since it has now been resolved. Let me know if you'd like to reopen it.
